Changes to Bash bootstrapping code
I put all my best practice setup lines in _common.

From conversations with @perlpunk I think that the environments your
Bash code runs in would all have Bash 4.2+.
Bash 4.4 or higher would be something to aim for.

Since _common is a Bash library and not an executable the shebang line
is not needed, however it's probably there as a syntax highlighter hint
since there is no `.bash` extension on this file.
A better name might be `_common.bash` or `.common.bash` or
`lib/common.bash`.

I changed a couple scripts to use `#!/usr/bin/env bash` shebang lines.
This is my preference for all my open source Bash that needs to run
everywhere.
One cool aspect of this is on OSX where `/bin/bash` must be v3.2 you can
do:

    (shopt -s compat44) || die "Bash 5.0+ required. Try 'brew install bash'."

Since brew will install to `/usr/local/bin` and that always comes before
`/bin` in a standard/sane `PATH`, Mac users can use Bash 5 with scripts
without changing /bin/bash.

I realize that OSX is not a target env for you, but you could do the
same trick to require a newer Bash on Suse Linux which I understand is
still at 4.2.

Finally by source-ing _common first thing in all your scripts you can
skip the `set -e ...` code as _common does it for you.

diff --git a/_common b/_common
--- a/_common
+++ b/_common
@@ -1,4 +1,9 @@
-#!/bin/bash -e
+#!/bash
+
+# Strict Bash settings:
+set -o errexit -o errtrace -o nounset -o pipefail
+# If Bash 4.4+
+shopt -s inherit_errexit 2>/dev/null || true
 
 # Common shell script snippets to be used when interacting with openQA
 # instances, for example over openqa-cli.
@@ -6,6 +11,10 @@
 warn() ( printf '%s\n' "$@" >&2 )
 
 die() { warn "$@"; exit 1; }
+
+# Set minimal Bash to 4.2
+(shopt -s compat41) ||
+  die "Bash 4.2+ is required"
 
 enable_force_result=${enable_force_result:-false}
 
