Pick latest version only when Update path exists
Use the `osc meta` in combination with `osc dists` to submit to the most
recent :Update repo. Likely no need for more than two distribution to find the
desired one. `osc meta` returns 404 if the prj does not exist and this should
give a clue to pick the latest Update project even if it is included in `osc
dists`

https://progress.opensuse.org/issues/127037

diff --git a/os-autoinst-obs-auto-submit b/os-autoinst-obs-auto-submit
--- a/os-autoinst-obs-auto-submit
+++ b/os-autoinst-obs-auto-submit
@@ -18,10 +18,37 @@ XMLSTARLET=$(command -v xmlstarlet || true)
 # shellcheck source=/dev/null
 . "$(dirname "${BASH_SOURCE[0]}")"/_common
 
+check_project_exists() {
+    # ex: openSUSE:Backports:SLE-15-SP6
+    local prj="$1"
+    local rc=0
+    if [[ -z "$prj" ]]; then
+        echo "Error: No project provided." >&2
+        return 1
+    fi
+    # dont need the XML output for checking existence.
+    # if $prj does not exist return 404
+    osc meta prj "$prj" > /dev/null 2> /dev/null
+    rc=$?
+    if [[ "$rc" -eq 0 ]]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
 get_submit_target_extra_latest_version() {
     # awk iterates through all the fields in the match to avoid fixed position
     # and it should match with the part which starts with `submit_target_extra_project`+`:`
-    latest_submit_target_extra_version=$(osc dists | grep "$submit_target_extra_project" | awk -v prj="$submit_target_extra_project" '{for (i=1; i<=NF; i++) if ($i ~ "^" prj ":") print $i}' | sort --version-sort | tail -n 1)
+    version_sorted=$(osc dists | grep "$submit_target_extra_project" | awk -v prj="$submit_target_extra_project" '{for (i=1; i<=NF; i++) if ($i ~ "^" prj ":") print $i}' | sort --version-sort | tail -n 2 | tac)
+    local rc=0
+    latest_submit_target_extra_version=''
+    for version in $version_sorted; do
+        if check_project_exists "${version}"; then
+            latest_submit_target_extra_version=$version && break
+        fi
+    done
+
     if [[ -z $latest_submit_target_extra_version ]]; then
         echo "Project not found." && return 1
     fi
@@ -261,4 +288,5 @@ prefix="${prefix:-""}"
 [ "$dry_run" = "1" ] && prefix="echo"
 osc="${osc:-"$prefix retry -e -- osc"}"
 
-caller 0 > /dev/null || submit "$@"
+#caller 0 > /dev/null || submit "$@"
+get_submit_target_extra_latest_version
