Prevent submission of failed packages from devel:openQA:tested to Factory
See https://progress.opensuse.org/issues/68260

diff --git a/os-autoinst-obs-auto-submit b/os-autoinst-obs-auto-submit
--- a/os-autoinst-obs-auto-submit
+++ b/os-autoinst-obs-auto-submit
@@ -7,6 +7,8 @@ src_project="${src_project:-"devel:openQA"}"
 dst_project="${dst_project:-"${src_project}:tested"}"
 submit_target="${submit_target:-"openSUSE:Factory"}"
 dry_run="${dry_run:-"0"}"
+osc_poll_interval="${osc_poll_interval:-2}"
+osc_build_start_poll_tries="${osc_build_start_poll_tries:-5}"
 XMLSTARLET=$(command -v xmlstarlet || true)
 [[ -n $XMLSTARLET ]] || (echo "Need xmlstarlet" && exit 1)
 
@@ -42,6 +44,27 @@ update_package() {
     else
         $osc ci -m "Offline generation of ${version}"
     fi
+    local osc_query="https://api.opensuse.org/public/build/$dst_project/_result?repository=$submit_target&package=$package"
+    local wip_states='\(unknown\|blocked\|scheduled\|dispatching\|building\|signing\|finished\)'
+    local bad_states='\(failed\|unresolvable\|broken\)'
+    local attempts="$osc_build_start_poll_tries"
+    while ! curl -s  "$osc_query" | grep -e "$wip_states" ; do
+        if [[ $attempts -le 0 ]]; then
+            echo "warning: Re-build of $package has not been considered in time (or package has been re-built so fast that we've missed it)"
+            break
+        fi
+        echo "Waiting for re-build of $package to be considered (attempts left: $attempts)"
+        sleep "$osc_poll_interval"
+        attempts=$((attempts - 1))
+    done
+    while curl -s "$osc_query" | grep -e "$wip_states" ; do
+        echo "Waiting while $package is in progress"
+        sleep "$osc_poll_interval"
+    done
+    if curl -s "$osc_query" | grep -e "$bad_states" ; then
+        echo "Building $package has failed, skipping submission"
+        return 1
+    fi
     cmd="$osc sr"
     req=$(factory_request "$package")
     # TODO: check if it's a different revision than HEAD
@@ -56,7 +79,7 @@ last_revision() {
     package=$2
     file=$package.changes
     service=obs_scm
-    if [[ $project != $submit_target ]]; then
+    if [[ $project != "$submit_target" ]]; then
        file=_service:$service:$file
     fi
     local line
